inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '') %>
    - <% end %>
    - "db/migrate/*"
    - "db/schema.rb"
  SuggestExtensions: false

require: rubocop-rspec
