test:
  mysql41: 9308
  min_infix_len: 1
  real_time_callbacks: false


development:
  mysql41: 9306
  min_infix_len: 1
  enable_star: 1

production:
  dict: keywords
  mysql41: <%= ENV['FLYING_SPHINX_PORT'] || 9306 %>
  host: <%= ENV['FLYING_SPHINX_HOST'] %>
  port: <%= ENV['FLYING_SPHINX_PORT'] %>
